--[[

	This file is part of 'Masque: Darion', an add-on for World of Warcraft.

	* File...: Darion.lua
	* Author.: Darsain

	Darion Skin

]]

local MSQ = LibStub and LibStub("Masque", true)
if not MSQ then return end

-----------------------------------------
-- Locals
---

local API_VERSION = 110000

-- Skin Info
local Version = "11.0.0"

----------------------------------------
-- Darion
---

MSQ:AddSkin("Darion", {
	API_VERSION = API_VERSION,
	Shape = "Square",

	-- [ Info ]
	Author = "Darsain",
	Description = "Darion skin for Masque.",
	Version = Version,

	-- [ Skin ]
	-- Mask = nil,
	Backdrop = {
		Texture = [[Interface\AddOns\Masque_Darion\Textures\Backdrop]],
		-- TexCoords = {0, 1, 0, 1},
		Color = {0.3, 0.3, 0.3, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "BACKGROUND",
		-- DrawLevel = -1,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseColor = nil,
	},
	Icon = {
		Texture = [[Interface\Icons\INV_Misc_Bag_08]],
		TexCoords = {0.02, 0.98, 0.02, 0.98},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "BACKGROUND",
		-- DrawLevel = 0,
		Width = 34,
		Height = 34,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	SlotIcon = "Icon",
	-- Shadow = nil,
	Normal = {
		Texture = [[Interface\AddOns\Masque_Darion\Textures\Normal]],
		-- TexCoords = {0, 1, 0, 1},
		Color = {0, 0, 0, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Darion\Textures\Normal]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {0, 0, 0, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseStates = nil,
	},
	-- Disabled = Default.Disabled,
	Pushed = {
		Texture = [[Interface\AddOns\Masque_Darion\Textures\Overlay]],
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseColor = nil,
	},
	Flash = {
		Texture = [[Interface\AddOns\Masque_Darion\Textures\Overlay]],
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 1,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseColor = nil,
	},
	Checked = {
		Texture = [[Interface\AddOns\Masque_Darion\Textures\Highlight]],
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		BlendMode = "ADD",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	SlotHighlight = "Checked",
	Border = {
		Texture = [[Interface\AddOns\Masque_Darion\Textures\Border]],
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	DebuffBorder = "Border",
	EnchantBorder = "Border",
	IconBorder = "Border",
	Gloss = {
		Texture = [[Interface\AddOns\Masque_Darion\Textures\Gloss]],
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	-- NewAction = Default.NewAction,
	-- SpellHighlight = Default.SpellHighlight,
	AutoCastable = {
		Texture = [[Interface\Buttons\UI-AutoCastableOverlay]],
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 1,
		Width = 34,
		Height = 34,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		OffsetX = 0.5,
		OffsetY = -0.5,
		-- SetAllPoints = nil,
	},
	-- IconOverlay = Default.IconOverlay,
	-- UpgradeIcon = Default.UpgradeIcon,
	-- IconOverlay2 = Default.IconOverlay2,
	-- QuestBorder = Default.QuestBorder,
	-- NewItem = Default.NewItem,
	-- SearchOverlay = Default.SearchOverlay,
	-- ContextOverlay = Default.ContextOverlay,
	-- JunkIcon = Default.JunkIcon,
	Duration = {
		-- JustifyH = "CENTER",
		-- JustifyV = "MIDDLE",
		-- DrawLayer = "OVERLAY",
		Width = 32,
		Height = 10,
		-- Anchor = nil,
		-- Point = "TOP",
		-- RelPoint = "BOTTOM",
		-- OffsetX = 0,
		OffsetY = -2,
	},
	Name = {
		-- JustifyH = "CENTER",
		-- JustifyV = "MIDDLE",
		-- DrawLayer = "OVERLAY",
		Width = 32,
		Height = 10,
		-- Anchor = nil,
		-- Point = "BOTTOM",
		-- RelPoint = "BOTTOM",
		-- OffsetX = 0,
		OffsetY = 5,
	},
	Highlight = {
		Texture = [[Interface\AddOns\Masque_Darion\Textures\Highlight]],
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "ADD",
		-- DrawLayer = "HIGHLIGHT",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseColor = nil,
	},
	-- [ AutoCastOverlay (Retail) ]
	-- AutoCast_Frame = Default.AutoCast_Frame,
	-- AutoCast_Shine = Default.AutoCast_Shine,
	-- [ AutoCastShine (Classic) ]
	AutoCast_Mask = {
		-- Atlas = "UI-HUD-ActionBar-PetAutoCast-Mask",
		-- UseAtlasSize = false,
		Texture = [[Interface\AddOns\Masque\Textures\Square\AutoCast-Mask]],
		-- TexCoords = {0, 1, 0, 1},
		Width = 30,
		Height = 30,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	AutoCast_Corners = {
		-- Atlas = "UI-HUD-ActionBar-PetAutoCast-Corners",
		-- UseAtlasSize = false,
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 1,
		Width = 38,
		Height = 38,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = true,
	},
	-- [ AutoCastShine (Classic) ]
	AutoCastShine = {
		Width = 26,
		Height = 26,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		OffsetX = 1,
		OffsetY = -1,
	},
	-- [ Cooldown ]
	Cooldown = {
		-- Texture = [[Interface\AddOns\Masque\Textures\Square\Mask]],
		-- EdgeTexture = [[Interface\AddOns\Masque\Textures\Square\Edge]],
		-- PulseTexture = [[Interface\Cooldown\star4]],
		-- Color = {0, 0, 0, 0.8},
		Width = 34,
		Height = 34,
		-- Anchor = nil,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	ChargeCooldown = "Cooldown",
	-- [ SpellAlert ]
	SpellAlert = {
		Height = 38,
		Width = 38,
		Classic = {
			Height = 32,
			Width = 32,
		},
		Modern = {
			Height = 30,
			Width = 30,
		},
		Thin = {
			Height = 28,
			Width = 28,
		},
	},
	-- [ TextOverlayContainer (Retail) ]
	HotKey = {
		-- JustifyH = "RIGHT",
		-- JustifyV = "MIDDLE",
		-- DrawLayer = "OVERLAY",
		Width = 32,
		Height = 10,
		-- Anchor = nil,
		-- Point = "TOPRIGHT",
		-- RelPoint = "TOPRIGHT",
		OffsetX = 4,
		OffsetY = -6,
	},
	Count = {
		-- JustifyH = "RIGHT",
		-- JustifyV = "MIDDLE",
		-- DrawLayer = "OVERLAY",
		Width = 32,
		Height = 10,
		-- Anchor = nil,
		-- Point = "BOTTOMRIGHT",
		-- RelPoint = "BOTTOMRIGHT",
		OffsetX = -4,
		OffsetY = 5,
	},
}, true)

----------------------------------------
-- Darion Clean
---

MSQ:AddSkin("Darion Clean", {
	Template = "Darion",

	-- [ Info ]
	Description = "Darion Clean skin for Masque.",

	-- [ Skin ]
	-- Mask = Template.Mask,
	-- Backdrop = Template.Backdrop,
	-- Icon = Template.Icon,
	-- SlotIcon = Template.SlotIcon,
	-- Shadow = Template.Shadow,
	Normal = {
		Texture = [[Interface\AddOns\Masque_Darion\Textures\Normal_clean]],
		-- TexCoords = {0, 1, 0, 1},
		Color = {0.2, 0.2, 0.2, 1},
		-- EmptyTexture = [[Interface\AddOns\Masque_Darion\Textures\Normal_clean]],
		-- EmptyCoords = {0, 1, 0, 1},
		-- EmptyColor = {0.2, 0.2, 0.2, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "ARTWORK",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
		-- UseStates = nil,
	},
	-- Disabled = Template.Disabled,
	-- Pushed = Template.Pushed,
	-- Flash = Template.Flash,
	-- Checked = Template.Checked,
	-- SlotHighlight = Template.SlotHighlight,
	-- Border = Template.Border,
	-- DebuffBorder = Template.DebuffBorder,
	-- EnchantBorder = Template.EnchantBorder,
	-- IconBorder = Template.IconBorder,
	Gloss = {
		Texture = [[Interface\AddOns\Masque_Darion\Textures\Gloss_clean]],
		-- TexCoords = {0, 1, 0, 1},
		-- Color = {1, 1, 1, 1},
		-- BlendMode = "BLEND",
		-- DrawLayer = "OVERLAY",
		-- DrawLevel = 0,
		Width = 40,
		Height = 40,
		-- Point = "CENTER",
		-- RelPoint = "CENTER",
		-- OffsetX = 0,
		-- OffsetY = 0,
		-- SetAllPoints = nil,
	},
	-- NewAction = Template.NewAction,
	-- SpellHighlight = Template.SpellHighlight,
	-- AutoCastable = Template.AutoCastable,
	-- IconOverlay = Template.IconOverlay,
	-- UpgradeIcon = Template.UpgradeIcon,
	-- IconOverlay2 = Template.IconOverlay2,
	-- QuestBorder = Template.QuestBorder,
	-- NewItem = Template.NewItem,
	-- SearchOverlay = Template.SearchOverlay,
	-- ContextOverlay = Template.ContextOverlay,
	-- JunkIcon = Template.JunkIcon,
	-- Duration = Template.Duration,
	-- Name = Template.Name,
	-- Highlight = Template.Highlight,
	-- [ AutoCastOverlay (Retail) ]
	-- AutoCast_Frame = Template.AutoCast_Frame,
	-- AutoCast_Shine = Template.AutoCast_Shine,
	-- AutoCast_Mask = Template.AutoCast_Mask,
	-- AutoCast_Corners = Template.AutoCast_Corners,
	-- [ AutoCastShine (Classic) ]
	-- AutoCastShine = Template.AutoCastShine,
	-- [ Cooldown ]
	-- Cooldown = Template.Cooldown,
	-- ChargeCooldown = Template.ChargeCooldown,
	-- [ SpellAlert ]
	-- SpellAlert = Template.SpellAlert,
	-- [ TextOverlayContainer (Retail) ]
	-- HotKey = Template.HotKey,
	-- Count = Template.Count,
}, true)
